//! Property-based tests for the raking pipeline.
//!
//! Cases are generated by drawing a hidden positive "true weight" per record
//! and deriving the marginal targets from it, so every generated problem has
//! consistent grand totals and is feasible on the seed's support.

use ipf_survey::{
    CodedSurvey, Normalization, PopulationTargets, RakingConfig, RakingError, ValidatedTargets,
    Variable, rake, rake_simple,
};
use proptest::prelude::*;

#[derive(Debug, Clone)]
struct Case {
    levels: Vec<usize>,
    codes: Vec<usize>,
    base_weights: Option<Vec<f64>>,
    true_weights: Vec<f64>,
}

impl Case {
    fn n_records(&self) -> usize {
        self.true_weights.len()
    }

    fn n_variables(&self) -> usize {
        self.levels.len()
    }

    fn survey(&self) -> CodedSurvey {
        let vars: Vec<Variable> = self
            .levels
            .iter()
            .enumerate()
            .map(|(i, &levels)| Variable {
                name: format!("v{i}"),
                levels,
                labels: None,
            })
            .collect();
        match &self.base_weights {
            Some(bw) => CodedSurvey::from_flat_codes_weighted(
                vars,
                self.codes.clone(),
                self.n_records(),
                bw.clone(),
            ),
            None => CodedSurvey::from_flat_codes(vars, self.codes.clone(), self.n_records()),
        }
        .expect("generated survey must be valid")
    }

    /// Marginal sums of `true_weights`: consistent and feasible by construction.
    fn target_vectors(&self) -> Vec<Vec<f64>> {
        let k = self.n_variables();
        (0..k)
            .map(|v| {
                let mut t = vec![0.0; self.levels[v]];
                for (r, &w) in self.true_weights.iter().enumerate() {
                    t[self.codes[r * k + v]] += w;
                }
                t
            })
            .collect()
    }

    fn targets(&self, survey: &CodedSurvey) -> ValidatedTargets {
        let mut pt = PopulationTargets::new();
        for (v, t) in self.target_vectors().into_iter().enumerate() {
            pt = pt.add(&format!("v{v}"), t);
        }
        pt.validate(survey).expect("derived targets must validate")
    }

    fn weighted_marginals(&self, weights: &[f64]) -> Vec<Vec<f64>> {
        let k = self.n_variables();
        (0..k)
            .map(|v| {
                let mut m = vec![0.0; self.levels[v]];
                for (r, &w) in weights.iter().enumerate() {
                    m[self.codes[r * k + v]] += w;
                }
                m
            })
            .collect()
    }

    fn base_weight(&self, r: usize) -> f64 {
        self.base_weights.as_ref().map_or(1.0, |bw| bw[r])
    }
}

fn case_strategy() -> impl Strategy<Value = Case> {
    (1_usize..=3, 1_usize..=40)
        .prop_flat_map(|(k, n)| (proptest::collection::vec(2_usize..=4, k), Just(n)))
        .prop_flat_map(|(levels, n)| {
            let record: Vec<_> = levels.iter().map(|&l| 0..l).collect();
            (
                Just(levels),
                proptest::collection::vec(record, n),
                proptest::option::of(proptest::collection::vec(0.25_f64..4.0, n)),
                proptest::collection::vec(0.1_f64..10.0, n),
            )
        })
        .prop_map(|(levels, records, base_weights, true_weights)| Case {
            levels,
            codes: records.into_iter().flatten().collect(),
            base_weights,
            true_weights,
        })
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(128))]

    /// Unbounded raking converges, weights sum to the grand total, and the
    /// weighted marginals reproduce the targets.
    #[test]
    fn marginals_match_targets(case in case_strategy()) {
        let survey = case.survey();
        let targets = case.targets(&survey);
        let result = rake_simple(&survey, &targets).unwrap();

        prop_assert!(result.convergence.converged, "IPF did not converge");

        let grand_total: f64 = case.true_weights.iter().sum();
        let tol = 1e-6 * grand_total.max(1.0);

        let sum: f64 = result.weights.iter().sum();
        prop_assert!(
            (sum - grand_total).abs() <= tol,
            "weight sum {sum} != grand total {grand_total}"
        );

        let marginals = case.weighted_marginals(&result.weights);
        for (v, (m, t)) in marginals.iter().zip(case.target_vectors()).enumerate() {
            for (l, (&got, want)) in m.iter().zip(t).enumerate() {
                prop_assert!(
                    (got - want).abs() <= tol,
                    "marginal v{v}[{l}] = {got}, target {want}"
                );
            }
        }
    }

    /// ESS <= n (Cauchy-Schwarz) and DEFF >= 1 on every successful rake.
    #[test]
    fn diagnostics_invariants(case in case_strategy()) {
        let survey = case.survey();
        let targets = case.targets(&survey);
        let result = rake_simple(&survey, &targets).unwrap();

        let n = case.n_records() as f64;
        let ess = result.diagnostics.effective_sample_size;
        prop_assert!(ess <= n + 1e-9, "ESS {ess} > n {n}");
        prop_assert!(
            result.diagnostics.design_effect >= 1.0 - 1e-9,
            "DEFF {} < 1",
            result.diagnostics.design_effect
        );
    }

    /// Every normalization mode hits its promised total.
    #[test]
    fn normalization_sums(case in case_strategy()) {
        let survey = case.survey();
        let targets = case.targets(&survey);
        let n = case.n_records() as f64;

        for (mode, want) in [
            (Normalization::SumToN, n),
            (Normalization::SumTo(123.45), 123.45),
            (Normalization::MeanOne, n),
        ] {
            let config = RakingConfig {
                normalization: mode,
                ..Default::default()
            };
            let result = rake(&survey, &targets, &config).unwrap();
            let sum: f64 = result.weights.iter().sum();
            prop_assert!(
                (sum - want).abs() <= 1e-6 * want.max(1.0),
                "sum {sum} != {want} under {mode:?}"
            );
        }
    }

    /// When trimming succeeds, every adjustment factor respects the bounds
    /// and the weighted marginals still match the targets. Infeasible bounds
    /// must fail with a trim-specific error, never a wrong answer.
    #[test]
    fn trimmed_factors_within_bounds(case in case_strategy()) {
        let survey = case.survey();
        let targets = case.targets(&survey);
        let (lo, hi) = (0.5, 2.0);
        let config = RakingConfig {
            weight_bounds: Some((lo, hi)),
            ..Default::default()
        };

        match rake(&survey, &targets, &config) {
            Ok(result) => {
                prop_assert!(result.convergence.converged);

                for r in 0..case.n_records() {
                    let factor = result.weights[r] / case.base_weight(r);
                    prop_assert!(
                        (lo - 1e-5..=hi + 1e-5).contains(&factor),
                        "record {r}: factor {factor} outside [{lo}, {hi}]"
                    );
                }

                let grand_total: f64 = case.true_weights.iter().sum();
                let tol = 1e-6 * grand_total.max(1.0);
                let marginals = case.weighted_marginals(&result.weights);
                for (v, (m, t)) in marginals.iter().zip(case.target_vectors()).enumerate() {
                    for (l, (&got, want)) in m.iter().zip(t).enumerate() {
                        prop_assert!(
                            (got - want).abs() <= tol,
                            "post-trim marginal v{v}[{l}] = {got}, target {want}"
                        );
                    }
                }
            }
            Err(RakingError::TrimInfeasible { .. } | RakingError::TrimNotConverged { .. }) => {}
            Err(e) => prop_assert!(false, "unexpected error: {e}"),
        }
    }

    /// One record per cell with targets equal to the seed counts is the
    /// identity problem: every weight comes back ~1.0.
    #[test]
    fn uniform_identity(shape in proptest::collection::vec(2_usize..=4, 1..=3)) {
        let n: usize = shape.iter().product();
        let k = shape.len();

        let mut strides = vec![1; k];
        for i in (0..k.saturating_sub(1)).rev() {
            strides[i] = strides[i + 1] * shape[i + 1];
        }
        let codes: Vec<usize> = (0..n)
            .flat_map(|cell| {
                let strides = &strides;
                let shape = &shape;
                (0..k).map(move |v| (cell / strides[v]) % shape[v])
            })
            .collect();

        let case = Case {
            levels: shape,
            codes,
            base_weights: None,
            true_weights: vec![1.0; n],
        };
        let survey = case.survey();
        let targets = case.targets(&survey);
        let result = rake_simple(&survey, &targets).unwrap();

        for (r, &w) in result.weights.iter().enumerate() {
            prop_assert!((w - 1.0).abs() < 1e-8, "weight[{r}] = {w}, expected 1.0");
        }
    }
}
